<?php

require_once '/home/sepdau/workspace/nevergiveup/protected/components/UserIdentity.php';

/**
 * Test class for UserIdentity.
 * Generated by PHPUnit on 2012-04-03 at 00:05:37.
 */
class UserIdentityTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var UserIdentity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserIdentity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers UserIdentity::authenticate
     * @todo Implement testAuthenticate().
     */
    public function testAuthenticate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
