<?php

require_once dirname(__FILE__) . '/../../../../../../../../../../var/www/nevergiveup/protected/tests/functional/SiteTest.php';

/**
 * Test class for SiteTest.
 * Generated by PHPUnit on 2012-04-07 at 22:20:46.
 */
class SiteTestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SiteTest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SiteTest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SiteTest::testIndex
     * @todo Implement testTestIndex().
     */
    public function testTestIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteTest::testContact
     * @todo Implement testTestContact().
     */
    public function testTestContact() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteTest::testLoginLogout
     * @todo Implement testTestLoginLogout().
     */
    public function testTestLoginLogout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
