<?php

require_once dirname(__FILE__) . '/../../../../../../../../../var/www/nevergiveup/protected/models/LoginForm.php';

/**
 * Test class for LoginForm.
 * Generated by PHPUnit on 2012-04-03 at 00:05:37.
 */
class LoginFormTest extends PHPUnit_Framework_TestCase {

    /**
     * @var LoginForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LoginForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers LoginForm::rules
     * @todo Implement testRules().
     */
    public function testRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginForm::attributeLabels
     * @todo Implement testAttributeLabels().
     */
    public function testAttributeLabels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginForm::authenticate
     * @todo Implement testAuthenticate().
     */
    public function testAuthenticate() {
       
    }

    /**
     * @covers LoginForm::login
     * @todo Implement testLogin().
     */
    public function testLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
