<?php

require_once dirname(__FILE__) . '/../../../../../../../../../var/www/nevergiveup/protected/tests/WebTestCase.php';

/**
 * Test class for WebTestCase.
 * Generated by PHPUnit on 2012-04-07 at 22:20:45.
 */
class WebTestCaseTest extends PHPUnit_Framework_TestCase {

    /**
     * @var WebTestCase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WebTestCase;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
