<?php

require_once dirname(__FILE__) . '/../../../../../../../../../../../../var/www/nevergiveup/protected/tests/unit/protected/controllers/SiteControllerTest.php';

/**
 * Test class for SiteControllerTest.
 * Generated by PHPUnit on 2012-04-07 at 22:20:47.
 */
class SiteControllerTestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SiteControllerTest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SiteControllerTest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SiteControllerTest::testActions
     * @todo Implement testTestActions().
     */
    public function testTestActions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteControllerTest::testActionIndex
     * @todo Implement testTestActionIndex().
     */
    public function testTestActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteControllerTest::testActionError
     * @todo Implement testTestActionError().
     */
    public function testTestActionError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteControllerTest::testActionContact
     * @todo Implement testTestActionContact().
     */
    public function testTestActionContact() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteControllerTest::testActionLogin
     * @todo Implement testTestActionLogin().
     */
    public function testTestActionLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteControllerTest::testActionLogout
     * @todo Implement testTestActionLogout().
     */
    public function testTestActionLogout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteControllerTest::testActionRegister
     * @todo Implement testTestActionRegister().
     */
    public function testTestActionRegister() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
