<?php

require_once dirname(__FILE__) . '/../../../../../../../../../var/www/nevergiveup/protected/controllers/SiteController.php';

/**
 * Test class for SiteController.
 * Generated by PHPUnit on 2012-04-03 at 00:09:48.
 */
class SiteControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SiteController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SiteController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SiteController::actions
     * @todo Implement testActions().
     */
    public function testActions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteController::actionIndex
     * @todo Implement testActionIndex().
     */
    public function testActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteController::actionError
     * @todo Implement testActionError().
     */
    public function testActionError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteController::actionContact
     * @todo Implement testActionContact().
     */
    public function testActionContact() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteController::actionLogin
     * @todo Implement testActionLogin().
     */
    public function testActionLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteController::actionLogout
     * @todo Implement testActionLogout().
     */
    public function testActionLogout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteController::actionRegister
     * @todo Implement testActionRegister().
     */
    public function testActionRegister() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
