<?php

require_once dirname(__FILE__) . '/../../../../../../../../../../../../var/www/nevergiveup/protected/tests/unit/protected/models/LoginFormTest.php';

/**
 * Test class for LoginFormTest.
 * Generated by PHPUnit on 2012-04-07 at 22:20:46.
 */
class LoginFormTestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var LoginFormTest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LoginFormTest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers LoginFormTest::testRules
     * @todo Implement testTestRules().
     */
    public function testTestRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginFormTest::testAttributeLabels
     * @todo Implement testTestAttributeLabels().
     */
    public function testTestAttributeLabels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginFormTest::testAuthenticate
     * @todo Implement testTestAuthenticate().
     */
    public function testTestAuthenticate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginFormTest::testLogin
     * @todo Implement testTestLogin().
     */
    public function testTestLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
