<?php

require_once dirname(__FILE__) . '/../../../../../../../../../../var/www/nevergiveup/protected/tests/unit/DbTest.php';

/**
 * Test class for DbTest.
 * Generated by PHPUnit on 2012-04-07 at 22:20:46.
 */
class DbTestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DbTest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DbTest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers DbTest::testConnection
     * @todo Implement testTestConnection().
     */
    public function testTestConnection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
